### ISSUE TITLE
analysis not replicable when seed= is specified

### ISSUE THREAD

**Issue by audrey-b** [audrey-b/simanalyse#3]
need to fix and add a test

**Comment by audrey-b** [comment]
sims <- sims_simulate("a ~ dnorm(mu,1)", 
                  parameters = nlist(mu=0), 
                  nsims=2)

sma_analyse_bayesian(sims=sims,
   code = "a ~ dnorm(mu,1)
                                 mu ~ dunif(-3,3)",
                         n.adapt = 101,
                        n.burnin = 0,
                         n.iter = 101,
                         monitor = "mu",
                         seed=56L)

sma_analyse_bayesian(sims=sims,
   code = "a ~ dnorm(mu,1)
                                 mu ~ dunif(-3,3)",
                         n.adapt = 101,
                        n.burnin = 0,
                         n.iter = 101,
                         monitor = "mu",
                         seed=56L)

**Comment by joethorley** [comment]
If you are using JAGS I don't think it can be replicable

https://sourceforge.net/p/mcmc-jags/discussion/610036/thread/eb142380a4/

**Comment by audrey-b** [comment]
I'm using a model block though. And when I set the seed outside sma_analyse_bayesian it is working, so I think it's only a matter of using set.seed(seed) inside the sma_analyse_bayesian, or setting .Random.seed <- seed inside the function depending whether seed should be an integer or a .Random.seed (still trying to wrap my head around the difference)

**Comment by joethorley** [comment]
Good point - ignore me!

You might find how sims handles seeds informative.
